version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskhub_db
    networks:
      - taskhub

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - taskhub
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - taskhub
    restart: unless-stopped

  app:
    build: .
    container_name: node_app
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq"
      REDIS_URL: "redis://redis:6379"  # Redis connection URL
    ports:
      - "3000:3000"
    networks:
      - taskhub
    restart: unless-stopped

networks:
  taskhub: